### ISSUE TITLE
inventory for each every department

### ISSUE THREAD

**Issue by lahirumadushanka** [buddhika75/prabhodha#30]
We need to maintain an inventory for every department which has inventory. For eg: Lab department has an inventory including lab reagents and chemicals at all times. The OPD has a particular drug inventory at all times. Are we able to manage these inventory via the present system?

This is not only for the lab. But for all departments maintaining any form (Drugs, X-ray sheets) of inventory.

**Comment by buddhika75** [comment]
It is already there. We can manage consumables and assests under Stores and Asset Management Module. It is already there, but we have not trained on that.

We can train for 4 days on that when Stores and Asset Management module is implemented after your request.

(Please respond and comment or close the issue)
