### ISSUE TITLE
transfer , recived  report is not visible with total items

### ISSUE THREAD

**Issue by ashanraveen** [buddhika75/prabhodha#31]
when we open transfer report via   "Pharmacy -> Transfer-> receive "  total items are not visible on the "View receive note"

![issue1](https://cloud.githubusercontent.com/assets/12614697/8006246/a72ffa50-0baf-11e5-98bd-0cde3d1f2674.png)

**Comment by rohanjayasundara** [comment]
Done. Please check and close.

**Comment by ashanraveen** [comment]
Working fine
