### ISSUE TITLE
Inventory

### ISSUE THREAD

**Issue by buddhika75** [buddhika75/prabhodha#8]
We need to maintain an inventory for every department which has inventory. For eg: Lab department has an inventory including lab reagents and chemicals at all times. The OPD has a particular drug inventory at all times. Are we able to manage these inventory via the present system?

**Comment by buddhika75** [comment]
This is not only for the lab. But for all departments maintaining any form (Drugs, X-ray sheets) of inventory.

**Comment by buddhika75** [comment]
Discussed with MLT earlier. Not finalized how items are automatically deducted. But if there is no need for automatic deduction. The other required functionality is already there. Please comment or close.

**Comment by ashanraveen** [comment]
t
